### ISSUE TITLE
SMM parameter

### ISSUE THREAD

**Issue by DIAMONDWHILE** [awai54st/PYNQ-Classification#10]
excuse me 
Can you tell me
SMM <1,75,32>(connect_1,connect_2,1,0,25); What is the meaning of each parameter?

**Comment by awai54st** [comment]
This function performs streaming matrix multiplication between matrices A and B.


template<
	unsigned A_COL_MAX,
	unsigned A_ROW_MAX,
	unsigned B_COL_MAX
>
void SMM(
	hls::stream<AXI_VAL> &in_stream_a, 
	hls::stream<AXI_VAL> &out_stream,
	const unsigned layer_id,
	const unsigned output_rectify,
	const int FACTOR
)

**Comment by DIAMONDWHILE** [comment]
Thanks for the help.

**Comment by awai54st** [comment]
Where A contains input activations, A_ROW=KER*KER*IN_CH. A_COL normally 1. B contains weights. B_COL=OUT_CH
