### ISSUE TITLE
output feature map 

### ISSUE THREAD

**Issue by DIAMONDWHILE** [awai54st/PYNQ-Classification#12]
Excuse me
What should I do if I want to output 13 * 13 * 125 in FPGAQuickTest ?

**Comment by awai54st** [comment]
Hi,
First you need to use the provided HLS project to synthesise a FPGA IP that does 13x13x125 output.
Once the bitstream is uploaded to the PYNQ board (in bitstream folder in the project), edit the parameters in the FPGAQuickTest function as follow:

`input_val = np.append([0, batch_size, KerDim, IFMCH, IFMDim, OFMCH, OFMDim, PadDim], input_val)`

Where you want OFMDim to be 13 and OFMCH to be 125.
I will re-upload my master thesis to the project, which contains the details of how the project has been designed.

Best,
awai54st

**Comment by stanely0714** [comment]
oh~ I see
thanks for the help
