### ISSUE TITLE
 fixed_point_stream_convolution

### ISSUE THREAD

**Issue by DIAMONDWHILE** [awai54st/PYNQ-Classification#19]
HI~
I want to look at the output characteristics of each layer, so I split the model.I found that the output feature map of the first convolutional layer is different from the first layer output performed by ARM.So I look at the fixed_point_stream_convolution.h file.In this file, why not multiply the input picture?

**Comment by awai54st** [comment]
Please specify: which part are you referring to? multiply with what?

**Comment by DIAMONDWHILE** [comment]
I use script_design_flow
Convolution in fixed_point_stream_convolution.h
Why is the output feature map of the first CONV1 output different from the CAFFE output feature map?

**Comment by awai54st** [comment]
For each layer, I scaled the weights and inputs with a scaling factor (to make them span the entire 8/16 bit signed int range) before casting them to fixed point for multiplication, such that the quantisation error is reduced (a somewhat inefficient implementation of "dynamic fixed point" quantisation). Hence, the output of each layer should also be scaled up as compared to the ARM benchmark, which uses floating point numbers.

So, ignoring the quantisation loss, the two output should also differ by a scaling factor.

**Comment by DIAMONDWHILE** [comment]
In HLS, my first layer of convolution is
AXI_DMA_SLAVE(in_stream, connect_0);
SCIG<3, 3, 416, 4, 416, 1> (connect_0, connect_1);
SMM<1, 27, 4>(connect_1, connect_2, 1, 0, 25);
AXI_DMA_MASTER(connect_2, out_stream);
And CAFFE's
Feat = net.blobs['conv1'].data[0, :4]
Vis_square(feat)
The output matrix gap is too large

**Comment by awai54st** [comment]
Your unrolling factor is 25 but the 2nd argument of SMM is 3x3x3=27. Vivado HLS expects the memory partitioning factor to be an integer factor of the memory size.

For debugging please write a HLS testbench about the first layer, and check the code’s correctness. The report provided in the repo should be enough to explain how the code works.

**Comment by Shanyuyinglou** [comment]
@DIAMONDWHILE 
Hi,I am using windows10 and it supports vivado 2016.2 version.I just tried to install Vivado HLx 2016.2 version,but it  has no vivado command prompt.It just has vivado tcl shell and vivado hls command prompt.I tried 2017.2 and 2018.1 version and they also have no vivado command tool.I do not know how it happened. Is there any other way to run vivado's command line ?I have been looking for information on the Internet for a long time but I have not found any relevant information.Please give me some advise.
Thanks.
In addition,I am using vivado WebPACK which is the no cost.Which edition did you use,WebPACK ,design edition or system edition?

**Comment by DIAMONDWHILE** [comment]
If I do not use "factors", how should I write
I want to confirm whether the reason for the failure is related to factors

**Comment by awai54st** [comment]
The failure is probably not about the factors, but it's worth noting. You can try a factor like 3, 9, or 27 instead of 25. Regarding the source of failure, I really cannot tell based on the provided information. Please try to debug by using a testbench.

**Comment by DIAMONDWHILE** [comment]
Could you teach me how to write a test bench?

**Comment by awai54st** [comment]
Guide [here](https://medium.com/@chathura.abeyrathne.lk/xilinx-vivado-hls-beginners-tutorial-custom-ip-core-design-for-fpga-59876d5a4119)

**Comment by DIAMONDWHILE** [comment]
I found that I changed the size of the image to 32 x 32 is the normal feature map
If the picture size is 416 x 416 it is not normal, which is why

**Comment by DIAMONDWHILE** [comment]
The problem is solved
Thanks for your help

**Comment by wangenyi** [comment]
hi 
  in script_design_flow,i can find axi_dma_slave/master and they connect the first  SCIG layer and the last FC layer  ,but in graphic_design_flow,i cant find them.why ?thank you!

**Comment by awai54st** [comment]
Good to know! @DIAMONDWHILE

**Comment by awai54st** [comment]
Answered [here](https://github.com/awai54st/PYNQ-Classification/issues/13#issuecomment-389147313).

Please do not duplicate your question on multiple issues.  @wangenyi
