### ISSUE TITLE
the usage 

### ISSUE THREAD

**Issue by sdnuzwk** [awai54st/PYNQ-Classification#24]
Dear Prof,
   Sorry to disturb you again!
   I  have a resource utilization issue that I want to discuss with you，because of the limitation of pynq board，if i want to design a deep net，the resource is not enough，so i  want to design a dropout layer after the pooling layer,my idea is multiply the output of the pooling layer by a constant less than 1，but  i don't know how to modify the code in the definition about the pooling layer ,could you give me some specific advices about the pooling code?

**Comment by sdnuzwk** [comment]
Sorry,another question，i want to know how to make sure the second parameter(A_ROW_MAX) of SMM,how to compute it?

**Comment by sdnuzwk** [comment]
Dear Prof,
   The FC layer is followed by the pool layer,how to make sure the second parameter of the FC layer,in your instructions,the second parametr is A_ROW_MAX=KER*KER*IN-CH。
   For example,in cifar 10,the code is 
        pool<2, 64, 8>(connect_8, connect_9, 3, 1, 0);
	FC<1, 1024, 64>(connect_9, connect_10, 4, 0, 32);
  so the 1024=4*4*64,so the KER is 4?Why?I am confused.i think it's 2

**Comment by sdnuzwk** [comment]
Today, i find a question,that's the sketchpad IP in graphical_design_flow,it includes many layer ips (i.e SCIG_CIF_0_1_0、SMM_CIF_0_1_0.......).From your instructions,the sketchpad is the ip for the project cifar 10,but i checked the main.cpp code in the SCIG_CIF_0_1 folder(in sketchpad ip)（a example）,the In_DIM parameter in  first layer of cifar 10 is 28,in fact it's 32,so i think it's not correct,could you help me,sir?

**Comment by sdnuzwk** [comment]
@awai54st

**Comment by awai54st** [comment]
Q1: Multiply your factor at line 172 of pool.h
Q2: I can't understand your question. For a FC layer, shouldn't the kernel size be 1?
Q3: The main.cpp is testbench, not the actual hardware. I used 28 for testing only. If you look at the CIFAR_10_wrapper.cpp (which is actually the hardware), then you can see that the input dimension is 32.

**Comment by sdnuzwk** [comment]
First of all, thank you for the guidance you gave me and help me a lot.
  The Q2:
  I wan to know compute  the second parameter of the FC layer,in your instructions,the second parametr is equal to  A_ROW_MAX=KER*KER*IN-CH。
For example,in cifar 10,the code is
pool<2, 64, 8>(connect_8, connect_9, 3, 1, 0);
FC<1, 1024, 64>(connect_9, connect_10, 4, 0, 32);
so the 1024 is the second parameter,1024=4*4*64,64 is the IN-CH,so the KER is 4?

**Comment by sdnuzwk** [comment]
![8qsznp dq9i 6 g sig](https://user-images.githubusercontent.com/35281365/41390211-3b7068c0-6fc7-11e8-8ec0-3a7c8c709cd5.png)
Dear Prof,
     Is the matrix multiplication picture right?In ADDITION1,the A2*B2 is added double，isn't it？

**Comment by awai54st** [comment]
In a fully connected layer, the operation is dot product between input feature map and weight matrix.
For your example, input frame has 4x4x64=1024 pixels. The corresponding weight matrix has 4x4x64x64 parameters, such that after dot product the output is in 1x1x64.

**Comment by awai54st** [comment]
You are right, the A2xB2 should only be accumulated once. Thank you!
I was trying to show that on FPGA a balanced adder tree has been synthesised for higher performance.
And I'm not a prof.

**Comment by sdnuzwk** [comment]
@awai54st Thank you very much ,prof.

**Comment by sdnuzwk** [comment]
@awai54st Dear Professor, I have a doubt. In your embodiment, the subgraph modes of SDFG and SDFG are implemented separately. My question is why there is no limit to the batch size in SDFG mode, but in the subgraph mode of SDFG. However, it is limited to 40. According to the truth, both modes use DDR buffers. Should the limit value be the same? Please help me answer the questions at a convenient time, thank you very much!

**Comment by sdnuzwk** [comment]
@awai54st Dear Professor, I have a doubt. In your embodiment, the subgraph modes of SDFG and SDFG are implemented separately. My question is why there is no limit to the batch size in SDFG mode, but in the subgraph mode of SDFG. However, it is limited to 40. According to the truth, both modes use DDR buffers. Should the limit value be the same? Please help me answer the questions at a convenient time, thank you very much!

**Comment by sdnuzwk** [comment]
@awai54st

**Comment by awai54st** [comment]
Hi, sorry for the late reply. Yes, I think you are right, they should have the same limit.

**Comment by sdnuzwk** [comment]
@awai54st Dear Professor, thank you for your detailed answers. In Section 6.2, you designed a single convolutional layer and tested resource usage with 32-bit floating point numbers. Can you guide me through the specific method steps? How do I change the code?

**Comment by awai54st** [comment]
You can look for the definition of AXI_VAL. Currently it is 8 or 16 bit fixed. Change it to float.  (PYNQ-Classification/hw/script_design_flow/LeNet_wrapper/config.h)

**Comment by sdnuzwk** [comment]
@awai54st If I want to test with just one convolution layer, how do I need to modify it in the cpp file?

**Comment by sdnuzwk** [comment]
@awai54st If I want to test with just one convolution layer, how do I need to modify it in the cpp file?

**Comment by sdnuzwk** [comment]
@awai54st If I want to test with just one convolution layer, how do I need to modify it in the cpp file?

**Comment by sdnuzwk** [comment]
@awai54st If I want to test with just one convolution layer, how do I need to modify it in the cpp file?

**Comment by awai54st** [comment]
You can make a CNN model with one layer.

**Comment by sdnuzwk** [comment]
@awai54st。Does a convolutional layer include the SGIG plus SMM functions or only the SGIG function?

**Comment by awai54st** [comment]
SCIG+SMM

**Comment by sdnuzwk** [comment]
@awai54st thank you very much, Rose

**Comment by sdnuzwk** [comment]
@awai54st Dear Professor, I am sorry to bother you. I designed a network myself, but why is the number of LUTs used far higher than the 53200? It should be reasonable to say that the resource utilization of BRAM and DSP is not very high.

**Comment by awai54st** [comment]
Hi, unfortunately I cannot help you with this. There are many possible reasons to that. I suggest that you have a look at the basics of low-level FPGA design.

**Comment by sdnuzwk** [comment]
@awai54st thank you very much,sir
