### ISSUE TITLE
Simple_sum, Mult_const and stream_mult IPs

### ISSUE THREAD

**Issue by saraballeri** [awai54st/PYNQ-Classification#28]
Hi,
I am studying your framework, but I have a doubt: what is the functionality of the simple_sum, mult_constant and stream_mult IPs? From their names I can guess but I do not understand how these IPs work with the IP of the network (e.g. cifar_10 IP). Can you clarify this please?

Thanks a lot,
Sara

**Comment by awai54st** [comment]
Hi, these were testing functions for the streaming interface during the early stage of development. Their functionalities are what their names suggest - summation, multiplication by a constant and multiplication of two data streams. They are no longer needed by this CNN project.
