### ISSUE TITLE
top files 

### ISSUE THREAD

**Issue by wangenyi** [awai54st/PYNQ-Classification#3]
hi, i want to finish the ip of convolution layers, but i do not know the top files when i try to add files to the HLS, i am a novice, so i want to know more details about this, i really thank you if you can help me.

**Comment by awai54st** [comment]
Hi, in the HLS directory the ***_wrapper.cpp file is the top file. For example, for LeNet the LeNet_wrapper/LeNet_wrapper.cpp is the top file for this IP.
