### ISSUE TITLE
about the im2col module

### ISSUE THREAD

**Issue by liubinfeng** [awai54st/PYNQ-Classification#34]
Hi,Mr.Wang. I'm now reading the im2col HLS code. I want to know why the size of the '**Initial_buffer**' was determined as
_Initial_buffer = MIN(Initial_lines * (IFMPadDim),IFMPadDim * IFMPadDim-1);_ 
and why there is one ' **additional_lines**' in the Initial_buffer?
_additional_lines = IFMPadDimSqrt/(OFMDim_curr * KerDim_curr * KerDim_curr);_
In my opinion , the size of 'Initial_buffer' just should be K * W
Can you give me some advice about it? thank  you~ ^_^

**Comment by awai54st** [comment]
Hi this code comes from a Xilinx example which is referenced in the main page. I will just try to explain it based on my understanding.
The intial_buffer variable is basically your K*W, with some corner cases being taken care of.
The additional_lines refer to the number of lines that the on-chip memory needs to accommodate when considering the input padding. Not sure why the function is in that form though.
