### ISSUE TITLE
SD card image

### ISSUE THREAD

**Issue by luckyboy234** [awai54st/PYNQ-Classification#38]
Hi，
I have got  a SD card image with pre-installed Caffe and Theano dependencies ,and I download your pynq-cnn-image file from Download Link(baidu drive)，and my board is pynq-z2 ,but the pynq-image fails to run on it .I am not sure if the image file can start my board ,or I have some mistakes about the image file?

**Comment by awai54st** [comment]
Hi, could you please specify how you downloaded the image and what you mean by "fails to run"?

**Comment by luckyboy234** [comment]
Hi,I have solved the problem.Thank you so much.And I have some new problems when I try to Build my CNN by using IP Blocks. I downloaded this file from Github. I followed the using guide in your paper,but I can not find the "CNN_BLOCK_DESIGN" mentioned in your paper. Maybe,I have some mistakes with this guide. I hope you can give m e some suggestions. Expect your reply! Thank you very much!
![image](https://user-images.githubusercontent.com/37886390/51109259-ad356d00-182f-11e9-9235-8abc6e52169e.png)

**Comment by awai54st** [comment]
This chapter was outdated. It refers to the "graphical design flow" in the project. Please see the guide provided in this repository instead.
Also, I recommend sticking to the "script design flow" instead - it is more stable than the graphical one.
