### ISSUE TITLE
Failed to import caffe on SD card image

### ISSUE THREAD

**Issue by brit95** [awai54st/PYNQ-Classification#41]
Hi, I downloaded the provided SD card image from the Google Drive link and attempted to run both the Lenet and CIFAR_10 Jupyter Notebook examples. It fails on the first step "Import Caffe" with the following error: 

ImportError                               Traceback (most recent call last)
<ipython-input-1-4c73f0708b4d> in <module>()
      2 caffe_root = '/home/xilinx/caffe/'  # this file should be run from {caffe_root}/examples (otherwise change this line)
      3 sys.path.insert(0, caffe_root + 'python')
----> 4 import caffe

/home/xilinx/caffe/python/caffe/__init__.py in <module>()
----> 1 from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
      2 from ._caffe import set_mode_cpu, set_mode_gpu, set_device, Layer, get_solver, layer_type_list, set_random_seed
      3 from ._caffe import __version__
      4 from .proto.caffe_pb2 import TRAIN, TEST
      5 from .classifier import Classifier

/home/xilinx/caffe/python/caffe/pycaffe.py in <module>()
     11 import numpy as np
     12 
---> 13 from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
     14         RMSPropSolver, AdaDeltaSolver, AdamSolver
     15 import caffe.io

ImportError: libprotobuf.so.10: cannot open shared object file: No such file or directory

**Comment by awai54st** [comment]
Hi, it appears that the libprotobuf package cannot be reached. Can you provide more information on this issue? What python kernel were you running on Jupyter Notebook? Was it python2?

**Comment by brit95** [comment]
I used the provided image from the link on your Github README. I just opened a notebook and printed the python version. It says it's using 3.4.3.

**Comment by awai54st** [comment]
Sorry for the late reply. The project doesn't support python 3 because at the time of developing the project python 3 doesn't support protobuf and caffe properly. Please switch to a python 2 kernel in the Jupyter notebook.
