### ISSUE TITLE
MicroSD card for PYNQ-Z2

### ISSUE THREAD

**Issue by ghost** [awai54st/PYNQ-Classification#44]
Hi, my name is Vladimir.
Can you help me with small question connect with Xilinx Pynq-z2
I want to use it and bought MicroSDHC 16GB, but my windows or Ubuntu don't see such drive, only device but drive letter don't appear. Maybe you know the reason? Thanks

**Comment by awai54st** [comment]
Hi Vladimir, 
Could be a bad connection? Or write protection (there should be a tiny switch on the card)?
Not sure -- maybe try contacting the card vendor.
