### ISSUE TITLE
Loading The Biases on To the FPGA !

### ISSUE THREAD

**Issue by hanaasal** [awai54st/PYNQ-Classification#57]
Hii!! I wanted to ask about the part in "Using a Caffe Pretrained Network - CIFAR10.ipynb" where you've loaded the weights on the FPGA. After that, I thought that the biases will be loaded as well on the FPGA, but it wasn't. Is there a specific reason behind not loading the biases and using them ?

**Comment by awai54st** [comment]
Hi, if I remember correctly my network was trained without biases. With small convolutional neural networks classifying small-scale datasets, biases are not that critical because we centralise the inputs anyway.
