### ISSUE TITLE
DMA Error caused by input images' pixels

### ISSUE THREAD

**Issue by farna-commits** [awai54st/PYNQ-Classification#58]
Hi,
We are facing an issue that we are unable to input test images with pixel values between 0 and 1. Whenever we try to do so the error "DMA Wait Timed Out". So is there anywhere in your code that we can change this restriction that does not allow to use image arrays with values between 0 ad 1?

**Comment by awai54st** [comment]
Hi,
If the only change that you intend to make is limiting the range of pixel values between 0 and 1, then I think the project should not have triggered this "DMA Wait Timed Out" error.
In another issue I talked about this error in greater detail (#53 ). I hope it is helpful to you.
