### ISSUE TITLE
Install Caffe on PYNQ failed at first step..

### ISSUE THREAD

**Issue by DINGJOY** [awai54st/PYNQ-Classification#6]
Hi,

I was trying to redo the project on my own PYNQ, but when I started to install the dependencies following the `MANUAL_INSTALL.md`, I failed at the first step with **`sudo apt-get install libprotobuf-dev libleveldb-dev libsnappy-dev libopencv-dev libhdf5-serial-dev protobuf-compiler`**..

The messages showed up as follow:
___
root@dingqiuyi:/home/xilinx# sudo apt-get install libprotobuf-dev libleveldb-dev libsnappy-dev libopencv-dev libhdf5-serial-dev prot
obuf-compiler
Reading package lists... Done
Building dependency tree
Reading state information... Done
libopencv-dev is already the newest version.
The following extra packages will be installed:
  hdf5-helpers libhdf5-10 libhdf5-cpp-10 libhdf5-dev libleveldb1v5 libprotobuf-lite9v5 libprotobuf9v5 libprotoc9v5 libsnappy1v5
Suggested packages:
  libhdf5-doc leveldb-doc
The following NEW packages will be installed:
  hdf5-helpers libhdf5-10 libhdf5-cpp-10 libhdf5-dev libhdf5-serial-dev libleveldb-dev libleveldb1v5 libprotobuf-dev
  libprotobuf-lite9v5 libprotobuf9v5 libprotoc9v5 libsnappy-dev libsnappy1v5 protobuf-compiler
0 upgraded, 14 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
Need to get 7,533 kB/7,570 kB of archives.
After this operation, 29.7 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
WARNING: The following packages cannot be authenticated!
  hdf5-helpers libhdf5-10 libhdf5-cpp-10 libhdf5-dev libhdf5-serial-dev libsnappy1v5 libleveldb1v5 libleveldb-dev
  libprotobuf-lite9v5 libprotobuf9v5 libprotoc9v5 libprotobuf-dev libsnappy-dev protobuf-compiler
Install these packages without verification? [y/N] y
Err http://ports.ubuntu.com/ubuntu-ports/ wily/universe hdf5-helpers armhf 1.8.15-patch1+docs-4
  404  Not Found [IP: 91.189.88.150 80]
Err http://ports.ubuntu.com/ubuntu-ports/ wily/universe libhdf5-10 armhf 1.8.15-patch1+docs-4
  404  Not Found [IP: 91.189.88.150 80]
Err http://ports.ubuntu.com/ubuntu-ports/ wily/universe libhdf5-cpp-10 armhf 1.8.15-patch1+docs-4
  404  Not Found [IP: 91.189.88.150 80]
Err http://ports.ubuntu.com/ubuntu-ports/ wily/universe libhdf5-dev armhf 1.8.15-patch1+docs-4
  404  Not Found [IP: 91.189.88.150 80]
Err http://ports.ubuntu.com/ubuntu-ports/ wily/universe libhdf5-serial-dev all 1.8.15-patch1+docs-4
  404  Not Found [IP: 91.189.88.150 80]
Err http://ports.ubuntu.com/ubuntu-ports/ wily/main libleveldb1v5 armhf 1.18-2.1ubuntu2
  404  Not Found [IP: 91.189.88.150 80]
Err http://ports.ubuntu.com/ubuntu-ports/ wily/main libleveldb-dev armhf 1.18-2.1ubuntu2
  404  Not Found [IP: 91.189.88.150 80]
Err http://ports.ubuntu.com/ubuntu-ports/ wily/main libprotobuf-lite9v5 armhf 2.6.1-1.2
  404  Not Found [IP: 91.189.88.150 80]
Err http://ports.ubuntu.com/ubuntu-ports/ wily/main libprotobuf9v5 armhf 2.6.1-1.2
  404  Not Found [IP: 91.189.88.150 80]
Err http://ports.ubuntu.com/ubuntu-ports/ wily/main libprotoc9v5 armhf 2.6.1-1.2
  404  Not Found [IP: 91.189.88.150 80]
Err http://ports.ubuntu.com/ubuntu-ports/ wily/main libprotobuf-dev armhf 2.6.1-1.2
  404  Not Found [IP: 91.189.88.150 80]
Err http://ports.ubuntu.com/ubuntu-ports/ wily/main protobuf-compiler armhf 2.6.1-1.2
  404  Not Found [IP: 91.189.88.150 80]
E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/pool/universe/h/hdf5/hdf5-helpers_1.8.15-patch1+docs-4_armhf.deb  404  Not F
ound [IP: 91.189.88.150 80]

E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/pool/universe/h/hdf5/libhdf5-10_1.8.15-patch1+docs-4_armhf.deb  404  Not Fou
nd [IP: 91.189.88.150 80]

E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/pool/universe/h/hdf5/libhdf5-cpp-10_1.8.15-patch1+docs-4_armhf.deb  404  Not
 Found [IP: 91.189.88.150 80]

E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/pool/universe/h/hdf5/libhdf5-dev_1.8.15-patch1+docs-4_armhf.deb  404  Not Fo
und [IP: 91.189.88.150 80]

E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/pool/universe/h/hdf5/libhdf5-serial-dev_1.8.15-patch1+docs-4_all.deb  404  N
ot Found [IP: 91.189.88.150 80]

E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/pool/main/l/leveldb/libleveldb1v5_1.18-2.1ubuntu2_armhf.deb  404  Not Found
[IP: 91.189.88.150 80]

E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/pool/main/l/leveldb/libleveldb-dev_1.18-2.1ubuntu2_armhf.deb  404  Not Found
 [IP: 91.189.88.150 80]

E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/pool/main/p/protobuf/libprotobuf-lite9v5_2.6.1-1.2_armhf.deb  404  Not Found
 [IP: 91.189.88.150 80]

E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/pool/main/p/protobuf/libprotobuf9v5_2.6.1-1.2_armhf.deb  404  Not Found [IP:
 91.189.88.150 80]

E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/pool/main/p/protobuf/libprotoc9v5_2.6.1-1.2_armhf.deb  404  Not Found [IP: 9
1.189.88.150 80]

E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/pool/main/p/protobuf/libprotobuf-dev_2.6.1-1.2_armhf.deb  404  Not Found [IP
: 91.189.88.150 80]

E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/pool/main/p/protobuf/protobuf-compiler_2.6.1-1.2_armhf.deb  404  Not Found [
IP: 91.189.88.150 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

___

Any suggestions how to solve this?

Thanks a lot!

**Comment by awai54st** [comment]
Hi,

I understand that manually installing the caffe dependencies is prone to errors, so if you want you can download the SD card images that I provided, which has all the dependencies pre-installed.

I have never seen this error before, but since it says 404 not found, I guess it’s either because your internet access does not allow accessing these addresses, or the apt-get package list is outdated?
