### ISSUE TITLE
Script Design Interface

### ISSUE THREAD

**Issue by Bahadiirr** [awai54st/PYNQ-Classification#61]
I run following codes:

vivado_hls -f run_cifar_10.tcl
vivado -source pynq_arch.tcl

But any project doesn't open in HLS or Vivado.

**Comment by Bahadiirr** [comment]
![image](https://user-images.githubusercontent.com/68679144/108374739-553d7180-7212-11eb-85a9-c3fd47e17785.png)

It's finished this

**Comment by awai54st** [comment]
Hi, the project was designed and tested with Vivado 16.2, and I haven't tried it with Vivado 19.1. Could you please switch to 16.2 and try it again? If that doesn't fix your issue, maybe try looking through the closed issues, and hopefully you can find answer there.
