### ISSUE TITLE
#Vivado version

### ISSUE THREAD

**Issue by quyenhooppa** [awai54st/PYNQ-Classification#62]
In step2, which version of Vivado can I use?? I'm using Vivado 2019.1, is this suitable?

**Comment by awai54st** [comment]
Hi, I recommend that you try 16.2 as that was the version that I used when developing this project.

**Comment by quyenhooppa** [comment]
Thanks for your reply. Is this suitable for Ultra96 v2?? I'm doing a project on Ultra96 v2 and I've found your repo.

**Comment by awai54st** [comment]
Not sure about Ultra96 as I've never tried before. I reckon that at least the hardware IPs should still be usable

**Comment by quyenhooppa** [comment]
Okay, thank you so much!
