### ISSUE TITLE
[BD 5-216] VLNV <xilinx.com:hls:FC_CIF_0_1:1.0> is not supported for the current part. 

### ISSUE THREAD

**Issue by Bahadiirr** [awai54st/PYNQ-Classification#64]
How to solve this error "[BD 5-216] VLNV <xilinx.com:hls:FC_CIF_0_1:1.0> is not supported for the current part. "
my block design
![image](https://user-images.githubusercontent.com/68679144/112473803-dc38b900-8d7f-11eb-9a4d-edaf461c4aa0.png)

**Comment by awai54st** [comment]
Hi, there appears to be a mismatch between the version of Vivado HLS (that you synthesised the fully connected layer, FC_CIF) and the version of Vivado that you are performing synthesis with. Could you please check their versions? The project was developed with 16.1.

Also, I notice that you are working with graphical flow. I recommend the script flow which is much more stable.
