### ISSUE TITLE
make compile_graphical failed

### ISSUE THREAD

**Issue by CHen-Hua-Luen** [awai54st/PYNQ-Classification#67]
您好，我在HLS Command Prompt 输入make compile_graphical后，Vivado自动打开，并且有Error，想起问您该怎么处理? 是否有可能因为我是在Windows下执行? 若改用Linux的话有可能解决吗? 谢谢您
![make compile_graphical_failed](https://user-images.githubusercontent.com/57308464/115694720-b78e2c00-a393-11eb-9521-d34db2351ea2.png)
![make compile_graphical_failed_terminal](https://user-images.githubusercontent.com/57308464/115694728-b957ef80-a393-11eb-8ab5-55efc0b282db.png)
![make compile_graphical_failed1](https://user-images.githubusercontent.com/57308464/115694730-b957ef80-a393-11eb-8b5d-3a96e9fb8c35.png)
![make compile_graphical_failed2](https://user-images.githubusercontent.com/57308464/115694732-b9f08600-a393-11eb-834d-9aa885c472ef.png)

**Comment by awai54st** [comment]
您好，graphical design flow有很多用户反馈说不稳定。所以我建议你使用script flow来设计。

**Comment by CHen-Hua-Luen** [comment]
谢谢
