### ISSUE TITLE
lenet graphical design file

### ISSUE THREAD

**Issue by mustafatasci42** [awai54st/PYNQ-Classification#73]
i want to study lenet graphical design files how can i access these files.

**Comment by awai54st** [comment]
Hi. What design files do you refer to? For the C++ HLS source files please see [here](https://github.com/awai54st/PYNQ-Classification/tree/master/hw/graphic_design_flow/CIFAR-10). For the tcl script that generates the vivado IP block containing the network, please see [here](https://github.com/awai54st/PYNQ-Classification/tree/master/hw/graphic_design_flow/CIFAR-10/SKETCHPAD). The generation of IPs has been automated by the Makefile (as explained in [here](https://github.com/awai54st/PYNQ-Classification/blob/master/hw/README.md)).

Please be adviced that the graphical design flow, as suggested by many users' feedback, is less stable than the script design flow. Please use the latter instead.

**Comment by mustafatasci42** [comment]
thanks for your reply. I rebuilt the rtl files
